spring.application.name=zonestyleapi
spring.datasource.url=jdbc:mysql://localhost:3306/zonestyle_db
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true