spring.application.name=T1_SantillanMaycol
spring.datasource.url=jdbc:mysql://localhost:3306/db_avion_santillan
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true